remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Abigale Wee]
description: [hi! welcome to my site. feel free to explore my ramblings, creative messes, and burning questions here.]
